name: shapepipe
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21.2.4
  - astromatic-psfex==3.21.1
  - astromatic-source-extractor==2.25.0
  - astropy==5.1
  - automake
  - autoconf
  - cmake
  - galsim
  - joblib
  - libtool
  - matplotlib
  - numba==0.55.2
  - numpy==1.22
  - pandas==2.2.2
  - pip:
    - cs_util
    - ngmix==2.3.1
    - mccd==1.2.3
    - modopt
    - PyQt5
    - pyqtgraph
    - python-pysap==0.2.1
    - reproject
    - skaha
    - sip_tpv
    - sf_tools
    - sqlitedict
    - termcolor
    - tqdm
    - treecorr
    - vos
    - git+https://github.com/tobias-liaudat/Stile@v0.1
